#!/usr/bin/env bash

main() {
  path=$(find ~/workspace ~/personal-projects ~ -mindepth 1 -maxdepth 1 -type d | fzf)

  if [[ -z $path ]]; then
    return
  fi

  session=$(basename $path | tr ':,. ' '____')

  if ! tmux has-session -t=$session 2>/dev/null; then
    tmux new-session -ds $session -c $path
    tmux-ready $session $path
  fi

  if [ $TMUX ]; then 
    tmux switch-client -t $session
  else
    tmux attach-session -t $session
  fi
}

main
